### ISSUE TITLE
Dongle.send() always returns with Error

### ISSUE THREAD

**Issue by samvidmistry** [Ubudu/Android-IOT-SDK#1]
Dongle.send() always returns with the error of "Data send timeout"

**Comment by MGasztold** [comment]
Hello,

Are you sure you are using version 1.4.1? Also please double check if the characteristic UUID that you use matches the one in the bluetooth device. 

Between 27th and 29th December there will be an update to this SDK with various bug fixes introduced while developing a real customer project using Ubudu dongles.

**Comment by samvidmistry** [comment]
Yes I am sure I am using 1.4.1. The server is also a mobile device, emulating the beacon as specified in SDK. I've tested it using my developed sample as well as samples found in the SDK. Both of them return the same error. Hopefully you have addressed the issue in the newer SDK.

**Comment by MGasztold** [comment]
What I would propose for now is using the following approach:

```
private static final String UB_SCANNER_PREFIX = "ubScanner-";

private BleDeviceFilter bleDeviceFilter = new BleDeviceFilter() {
        @Override
        public boolean isCorrect(BluetoothDevice device, int rssi, byte[] scanResponse) {
            return device.getName() != null && device.getName().startsWith(UB_SCANNER_PREFIX);
        }
    };
```
```
DiscoveryManager.discover(getApplicationContext(), 3000, bleDeviceFilter, mDiscoveryListener);
```

Then in your `mDiscoveryListener` callback named `onBleDeviceFound` you decide which device you want to use. You should call `connect` on it.

After successful connection you should do:

```
mBleDevice.setDataReceivedEventListener(mDataReceivedEventListener);
mBleDevice.discoverServices(new BleDevice.ServicesDiscoveryListener() {
            @Override
            public void onServicesDiscovered(final List<BluetoothGattService> services) {
                // select the service which characteristics you want to use
                // the default service UUID of the latest dongle is 
                // D9500001-F608-42CD-A37E-92A559491B2B
                for (BluetoothGattService service : services) {
                        if (service.getUuid().toString().equalsIgnoreCase("D9500001-F608-42CD-A37E-92A559491B2B")) {

                            // there should be TX characteristic D9500002-F608-42CD-A37E-92A559491B2B
                            for (BluetoothGattCharacteristic characteristic : service.getCharacteristics()) {
                                  if (characteristic.getUuid().toString().equalsIgnoreCase("D9500002-F608-42CD-A37E-92A559491B2B")) {
                                         mBleDevice.setGattCharacteristicForWriting(characteristic);
                                         break;
                                   }
                            }                            
                            break;
                        }
                }
            }

            @Override
            public void onError(Error error) {
                mBleDevice.disconnect();
            }
        });
```

I have tested IOT SDK v1.4.1 with a real dongle following the approach above and it worked without issues. Maybe it will help you.

Using Dongle package was done to reduce the boiler plate code needed for the generic way where you need to specify and pick everything on your own. I suspect that maybe the default UUIDs set for the Dongle in the IOT SDK do not match ones that are present in the Firmware of the dongle device you have.

**Comment by samvidmistry** [comment]
I think you're not understanding what my error is. You see, I am not using a real dongle. I have installed the UBIe application sample, that is available with the SDK, in a phone, which is working as peripheral. I have installed the same UBIe application as well as another demo that I coded, in another Android phone, which works as Client. Now I am trying to send data from client, to peripheral device. In the provided demo, there is only one service with UUID
`0000ffe0-0000-1000-8000-00805f9b34fb`
which connects. Other two services return "Connection Error: Could not register to read characteristic notifications".
Now in this service, we have two characteristics. Selecting one for notification characteristic and other for writing characteristic, We reach at the screen where we need to give input to be sent to the peripheral device. Now after writing data in box, when I press "SEND DATA" button, it always returns with an error of "Data Send Timeout".
I am talking about this code in MainActivity.java
```
@Override
    public void onSendMessageRequested(String message) {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M
                && ContextCompat.checkSelfPermission(getApplicationContext(), Manifest.permission.ACCESS_FINE_LOCATION) != PackageManager.PERMISSION_GRANTED) {
            requestPermissions(new String[]{Manifest.permission.ACCESS_FINE_LOCATION}, ASK_GEOLOCATION_PERMISSION_REQUEST_ON_SEND_DATA);
            return;
        }
        byte[] data = new byte[0];
        try {
            data = (message).getBytes("UTF-8");
        } catch (UnsupportedEncodingException e) {
            e.printStackTrace();
        }
        mBleDevice.send(data, new DataSentListener() {
            @Override
            public void onDataSent(byte[] data) {
                dismissProgressDialog();
                Log.i(TAG, "Data successfully sent: " + String.format("%020x", new BigInteger(1, data)));
                commFragment.onMessageSendingFinished();
            }

            @Override
            **public void onError(Error error) {
                Log.e(TAG, error.getLocalizedMessage());
                ToastUtil.showToast(getApplicationContext(), error.getLocalizedMessage());
                commFragment.onMessageSendingFinished();
            }**
        });
    }
```

Here, I never get a callback to onDataSent, instead it always goes into onError with the error of "Data send timeout".

**Comment by MGasztold** [comment]
Ok thanks, now I understand your issue. It will be fixed in the new release of IOT-SDK somewhere between 27th-29th of December. I will let you know here too.

**Comment by MGasztold** [comment]
Hello,

I have just pushed a release v1.5.0. Please check again the Readme.md for API changes and usage details.

Also the sample app has been refreshed. I have tested the peripheral feature. The foreign device is able to write data to it.

Let me know if you experience any issues.

**Comment by MGasztold** [comment]
Hello @samvidmistry ,

Is your issue solved now? Can I close this issue? Thank you :)
